spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/momently
    username: momently
    password: change-me
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
