package com.momently.orchestrator.domain;

/**
 * 오케스트레이터가 관리하는 워크플로의 생명주기 상태다.
 */
public enum WorkflowStatus {
    CREATED,
    PHOTO_INFO_EXTRACTING,
    PHOTO_INFO_EXTRACTED,
    PRIVACY_REVIEWING,
    PRIVACY_REVIEWED,
    QUALITY_SCORING,
    QUALITY_SCORED,
    PHOTO_GROUPING,
    PHOTO_GROUPED,
    HERO_PHOTO_SELECTING,
    HERO_PHOTO_SELECTED,
    OUTLINE_CREATING,
    OUTLINE_CREATED,
    DRAFT_CREATING,
    DRAFT_CREATED,
    STYLE_APPLYING,
    STYLE_APPLIED,
    REVIEWING,
    REVIEW_COMPLETED,
    COMPLETED,
    FAILED
}
